# Generated by Django 4.1 on 2022-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Owned_Date', models.DateField()),
                ('Satisfaction_level', models.CharField(choices=[('Very Satisfield', 'Very Satisfield'), ('Satisfield', 'Satisfield'), ('Okayish', 'Okayish'), ('Unsatisfield', 'Unsatisfield')], default='Very Satisfield', max_length=15)),
                ('Feedback', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
